
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/npm-install-next-build.sh
      runas: root
      timeout: 301
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60